version: '2'
services:
  #  app:
  #    image: app-spring-boot:latest
  #    build:
  #      context: .
  #    container_name: app
  #    depends_on:
  #      - mongo

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: wurstmeister/kafka
    # for testing/debugging purpose
    #    ports:
    #      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mail_topic:1:1"
    depends_on:
      - zookeeper
    networks:
      - backend

  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - "27017"
    networks:
      - backend

  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
      - kafka
    networks:
      - backend

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.10.1.0/16