version: '2'
services:
#  app:
#    image: app-spring-boot:latest
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - mongo

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "mail_topic:1:1"
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
      - kafka
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017